In [ ]:
%pip install imblearn

In [1]:
import numpy as np
import pandas as pd

from imblearn.over_sampling import SMOTE

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score,train_test_split,GridSearchCV

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import classification_report,roc_auc_score

In [2]:
df = pd.read_csv('../stroke_data_cleaned.csv')
df.head()

Unnamed: 0  gender   age  hypertension  heart_disease ever_married  \
0           0    Male  67.0             0              1          Yes   
1           1  Female  61.0             0              0          Yes   
2           2    Male  80.0             0              1          Yes   
3           3  Female  49.0             0              0          Yes   
4           4  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level        bmi  \
0        Private          Urban             228.69  36.600000   
1  Self-employed          Rural             202.21  28.893237   
2        Private          Rural             105.92  32.500000   
3        Private          Urban             171.23  34.400000   
4  Self-employed          Rural             174.12  24.000000   

    smoking_status  stroke           bmi_gr health_status        age_gr  
0  formerly smoked       1  Extremely Obese       hd_only           Old  
1     never smoked       1       Overweight    No disease           Old  
2     never smoked       1            Obese       hd_only           Old  
3           smokes       1            Obese    No disease  Mature Adult  
4     never smoked       1           Normal       ht only           Old

In [3]:
df.isnull().sum()

Unnamed: 0           0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
bmi_gr               0
health_status        0
age_gr               0
dtype: int64

In [4]:
df2 = df[df.columns[1:12]]
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             5110 non-null   object 
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64  
 3   heart_disease      5110 non-null   int64  
 4   ever_married       5110 non-null   object 
 5   work_type          5110 non-null   object 
 6   Residence_type     5110 non-null   object 
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                5110 non-null   float64
 9   smoking_status     5110 non-null   object 
 10  stroke             5110 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 439.3+ KB


In [5]:
gender_labels = {'Male':0,'Female':1}
ever_married_labels = {'Yes':0,'No':1}
work_type_labels = {'Private' : 0, 'Self-employed' : 1, 'Govt_job' : 2, 'children' : 3, 'Never_worked' : 4}
residence_type_labels = {'Urban' : 0, 'Rural' : 1}
smoking_status_labels = {'formerly smoked' : 0, 'never smoked' : 1, 'smokes' : 2, 'Unknown' : 3}

df2['gender'] = df2['gender'].map(gender_labels)
df2['ever_married'] = df2['ever_married'].map(ever_married_labels)
df2['work_type'] = df2['work_type'].map(work_type_labels)
df2['Residence_type'] = df2['Residence_type'].map(residence_type_labels)
df2['smoking_status'] = df2['smoking_status'].map(smoking_status_labels)

C:\Users\harsh\AppData\Local\Temp/ipykernel_5832/356677554.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['gender'] = df2['gender'].map(gender_labels)
C:\Users\harsh\AppData\Local\Temp/ipykernel_5832/356677554.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['ever_married'] = df2['ever_married'].map(ever_married_labels)
C:\Users\harsh\AppData\Local\Temp/ipykernel_5832/356677554.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[ro

In [6]:
X = df2.drop(columns=['stroke']).values
y = df2['stroke'].values

In [7]:
X

array([[  0.        ,  67.        ,   0.        , ..., 228.69      ,
         36.6       ,   0.        ],
       [  1.        ,  61.        ,   0.        , ..., 202.21      ,
         28.89323691,   1.        ],
       [  0.        ,  80.        ,   0.        , ..., 105.92      ,
         32.5       ,   1.        ],
       ...,
       [  1.        ,  35.        ,   0.        , ...,  82.99      ,
         30.6       ,   1.        ],
       [  0.        ,  51.        ,   0.        , ..., 166.29      ,
         25.6       ,   0.        ],
       [  1.        ,  44.        ,   0.        , ...,  85.28      ,
         26.2       ,   3.        ]])

In [8]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [9]:
X = MinMaxScaler().fit_transform(X)
X

array([[0.        , 0.81689453, 0.        , ..., 0.80126489, 0.30126002,
        0.        ],
       [1.        , 0.74365234, 0.        , ..., 0.67902317, 0.21298095,
        0.33333333],
       [0.        , 0.97558594, 0.        , ..., 0.23451205, 0.25429553,
        0.33333333],
       ...,
       [1.        , 0.42626953, 0.        , ..., 0.12865848, 0.2325315 ,
        0.33333333],
       [0.        , 0.62158203, 0.        , ..., 0.51320284, 0.17525773,
        0.        ],
       [1.        , 0.53613281, 0.        , ..., 0.13922999, 0.18213058,
        1.        ]])

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state = 65)

In [11]:
print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
x_train_res, y_train_res = sm.fit_resample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(x_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

Before OverSampling, counts of label '1': 174
Before OverSampling, counts of label '0': 3403 

After OverSampling, the shape of train_X: (6806, 10)
After OverSampling, the shape of train_y: (6806,) 

After OverSampling, counts of label '1': 3403
After OverSampling, counts of label '0': 3403


In [13]:
classifier = KNeighborsClassifier()
classifier.fit(x_train_res,y_train_res)

y_pred = classifier.predict(X_test)

In [14]:
accuracies = cross_val_score(
                estimator = classifier,
                X = x_train_res,
                y = y_train_res.ravel(),
                cv =10,
                scoring='accuracy'
            )

print('classification report:')
print(classification_report(y_test,y_pred))
print('roc_auc_score:')
print(roc_auc_score(y_test,y_pred))
print('cross validation mean accuracy:')
print(accuracies.mean()*100)

classification report:
              precision    recall  f1-score   support

           0       0.96      0.83      0.89      1458
           1       0.09      0.32      0.14        75

    accuracy                           0.80      1533
   macro avg       0.52      0.57      0.51      1533
weighted avg       0.92      0.80      0.85      1533

roc_auc_score:
0.5746090534979424
cross validation mean accuracy:
91.06651118597219


In [15]:
grid_params = {
                'n_neighbors':[5,7,8,10], 
                'metric': ['euclidean', 'manhattan', 'chebyshev', 'minkowski'],
                'weights': ['uniform','distance']
            }

In [16]:
grid_search = GridSearchCV(
                estimator = classifier,
                param_grid = grid_params,
                scoring = 'accuracy',
                cv = 10
            )

grid_search.fit(x_train_res,y_train_res)

print('best score:',grid_search.best_score_)
print('best params:',grid_search.best_params_)

bast score: 0.9290317007860412
best params: {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'distance'}


In [18]:
grid_search2 = GridSearchCV(
                estimator = classifier,
                param_grid = grid_params,
                scoring = 'recall',
                cv = 10
            )

grid_search2.fit(x_train_res,y_train_res)

print('best score:',grid_search2.best_score_)
print('best params:',grid_search2.best_params_)

bast score: 0.9917707434880111
best params: {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'distance'}


In [17]:
classifier = KNeighborsClassifier(
                n_neighbors = 5,
                metric = 'manhattan',
                weights = 'distance'
            )

classifier.fit(x_train_res,y_train_res)
y_pred = classifier.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.87      0.91      1458
           1       0.07      0.19      0.10        75

    accuracy                           0.84      1533
   macro avg       0.51      0.53      0.51      1533
weighted avg       0.91      0.84      0.87      1533



In [19]:
classifier2 = KNeighborsClassifier(
                n_neighbors = 7,
                metric = 'euclidean',
                weights = 'distance'
            )

classifier2.fit(x_train_res,y_train_res)
y_pred = classifier2.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.83      0.89      1458
           1       0.08      0.31      0.13        75

    accuracy                           0.80      1533
   macro avg       0.52      0.57      0.51      1533
weighted avg       0.92      0.80      0.85      1533

